version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15673:15672
  registry:
    image: tiny/registry
    ports:
      - "8761:8761"
  config:
    image: tiny/config
    ports:
      - "8888:8888"
  monitor:
    image: tiny/monitor
    ports:
      - "8040:8040"
  zipkin:
    image: tiny/zipkin
    ports:
      - "9411:9411"
  gateway:
    image: tiny/gateway
    ports:
      - "8060:8060"
  auth-service:
    image: tiny/auth-service
    ports:
      - "5000:5000"
  a-service:
    image: tiny/a-service
  b-service:
    image: tiny/b-service